package com.expanded.rails.mod;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

import com.expanded.rails.mod.blocks.*;
import com.expanded.rails.mod.gui.GuiHandlerRailsCraftingTable;
//import expanded.rails.mod.entity.TileEntityRailBrake;
//import expanded.rails.mod.entity.TileEntityRailBrakeEntity;
import com.expanded.rails.mod.gui.GuiHandlerRailsCraftingTable;
import com.expanded.rails.mod.gui.SlotRailsCraftingTable;
import com.expanded.rails.mod.rails.*;

@Mod(modid = "ExpandedRailsMod", name = "Expanded Rails Mod", version = "1.4.1")
public class ERMBase
{
	
	public static final String modid = "ExpandedRailsMod";
	
    // The instance of your mod that Forge uses.
    @Instance("ExpandedRailsMod")
    public static ERMBase instance;

    // Says where the client and server 'proxy' code is loaded.
    @SidedProxy(clientSide = "com.expanded.rails.mod.client.ClientProxy", serverSide = "com.expanded.rails.mod.CommonProxy")
    public static CommonProxy proxy;

    public static CreativeTabs tabNormalRails = new CreativeTabs("tabNormalRails") {
        public ItemStack getIconItemStack() {
                return new ItemStack(ERMBase.diamondRail, 1, 0);
        }

		@Override
		public Item getTabIconItem() {
			// TODO Auto-generated method stub
			return null;
		}
};
    public static CreativeTabs tabMonoRails = new CreativeTabs("tabMonoRails") {
        public ItemStack getIconItemStack() {
                return new ItemStack(ERMBase.monorailDiamond, 1, 0);
        }

		@Override
		public Item getTabIconItem() {
			// TODO Auto-generated method stub
			return null;
		}
};
	public static CreativeTabs tabTripleRails = new CreativeTabs("tabTripleRails") {
    public ItemStack getIconItemStack() {
            return new ItemStack(ERMBase.triplerailDiamond, 1, 0);
    }

	@Override
	public Item getTabIconItem() {
		// TODO Auto-generated method stub
		return null;
	}
};
    //Block blockIDs for config.cfg file registration in PreInit and block registration (block's ID itself) in Init.//
    //Custom Rails//
    public static int obsidianRailID;
    public static int diamondRailID;
    public static int lapisRailID;
    public static int iceRailID;
    public static int glowstoneRailID;
    public static int diamondNetherRailID;
    public static int diamondObsidianRailID;
    public static int brickRailID;
    public static int emeraldRailID;
    public static int netherStarRailID;
    public static int enderPearlRailID;
    public static int chainRailID;
    public static int armedRailID;
    //Wool Rails//
    public static int whiteWoolRailID;
    public static int orangeWoolRailID;
    public static int magentaWoolRailID;
    public static int lightblueWoolRailID;
    public static int yellowWoolRailID;
    public static int limeWoolRailID;
    public static int pinkWoolRailID;
    public static int grayWoolRailID;
    public static int lightgrayWoolRailID;
    public static int cyanWoolRailID;
    public static int purpleWoolRailID;
    public static int blueWoolRailID;
    public static int brownWoolRailID;
    public static int greenWoolRailID;
    public static int redWoolRailID;
    public static int blackWoolRailID;
    //Custom Blocks//
    public static int railsCraftingTableID;
    //public static int railBrakeID;
    //Monorails//
    public static int monorailDiamondID;
    public static int monorailGlowingID;
    public static int monorailNetherID;
    public static int monorailObsidianID;
    public static int monorailEmeraldID;
    public static int monorailLapisID;
    public static int monorailGoldID;
    public static int monorailPoweredID;
    public static int monorailIceID;
    public static int monorailChainID;
    public static int monorailArmedID;
    public static int monorailEnderPearlID;
    //Wool Monorails//
    public static int monorailWhiteID;
    public static int monorailOrangeID;
    public static int monorailMagentaID;
    public static int monorailLightblueID;
    public static int monorailYellowID;
    public static int monorailLimeID;
    public static int monorailPinkID;
    public static int monorailGrayID;
    public static int monorailLightgrayID;
    public static int monorailCyanID;
    public static int monorailPurpleID;
    public static int monorailBlueID;
    public static int monorailBrownID;
    public static int monorailGreenID;
    public static int monorailRedID;
    public static int monorailBlackID;
    public static int monorailGrayOrangeID;
    public static int monorailRedGreenID;
    public static int monorailYellowBlueID;
    //Triplerails//
    public static int triplerailDiamondID;
    public static int triplerailGlowingID;
    public static int triplerailNetherID;
    public static int triplerailObsidianID;
    public static int triplerailEmeraldID;
    public static int triplerailLapisID;
    public static int triplerailPoweredID;
    public static int triplerailIceID;
    public static int triplerailChainID;
    public static int triplerailArmedID;
    public static int triplerailEnderPearlID;
    //Wool Triplerails//
    public static int triplerailWhiteID;
    public static int triplerailOrangeID;
    public static int triplerailMagentaID;
    public static int triplerailLightblueID;
    public static int triplerailYellowID;
    public static int triplerailLimeID;
    public static int triplerailPinkID;
    public static int triplerailGrayID;
    public static int triplerailLightgrayID;
    public static int triplerailCyanID;
    public static int triplerailPurpleID;
    public static int triplerailBlueID;
    public static int triplerailBrownID;
    public static int triplerailGreenID;
    public static int triplerailRedID;
    public static int triplerailBlackID;
    //Item itemIDs for config.cfg file registration in PreInit and item registration (item's ID itself) in Init.//
    //Custom Items
    public static int emeraldBarID;
    public static int obsidianBarID;
    public static int diamondBarID;
    public static int lapisBarID;
    public static int ironNailID;
    public static int goldNailID;
    public static int diamondNailID;
    public static int emeraldNailID;
    public static int obsidianNailID;
    public static int netherrackNailID;
    public static int woolenNailID;
    public static int netherIngotID;
    public static int railIronBaseID;
    public static int railDiamondBaseID;
    public static int railObsidianBaseID;
    public static int railNetherrackBaseID;
    public static int railEmeraldBaseID;
    public static int railLapisBaseID;
    public static int railGoldBaseID;
    public static int railArmedBaseID;
    public static int railChainBaseID;
    public static int railIceBaseID;
    public static int railEnderPearlBaseID;
    public static int obsidianChunkID;
    public static int explosiveBarID;
    //Minecarts
    public static int minecartWhiteID;
    public static int minecartOrangeID;
    public static int minecartMagentaID;
    public static int minecartLightblueID;
    public static int minecartYellowID;
    public static int minecartLimeID;
    public static int minecartPinkID;
    public static int minecartGrayID;
    public static int minecartLightgrayID;
    public static int minecartCyanID;
    public static int minecartPurpleID;
    public static int minecartBlueID;
    public static int minecartBrownID;
    public static int minecartGreenID;
    public static int minecartRedID;
    public static int minecartBlackID;
    public static final int guiIDWorkSurface = 1;

    public static boolean configFlag;

    public static Block obsidianRail, diamondRail, lapisRail, iceRail, glowstoneRail, diamondNetherRail, diamondObsidianRail, brickRail, emeraldRail, netherStarRail, whiteWoolRail, orangeWoolRail, magentaWoolRail, lightblueWoolRail, yellowWoolRail, limeWoolRail, pinkWoolRail, grayWoolRail, lightgrayWoolRail, cyanWoolRail, purpleWoolRail, blueWoolRail, brownWoolRail, greenWoolRail, redWoolRail, blackWoolRail, enderPearlRail, chainRail, railsCraftingTable, armedRail, monorailDiamond, monorailGlowing, monorailGrayOrange, monorailNether, monorailObsidian, monorailRedGreen, monorailYellowBlue, monorailEmerald, monorailLapis, monorailGold, monorailPowered, monorailIce, monorailChain, monorailArmed, monorailEnderPearl;
    public static Block monorailWhite, monorailOrange, monorailMagenta, monorailLightblue, monorailYellow, monorailLime, monorailPink, monorailGray, monorailLightgray, monorailCyan, monorailPurple, monorailBlue, monorailBrown, monorailGreen, monorailRed, monorailBlack, railBrake;
    public static Block triplerailWhite, triplerailOrange, triplerailMagenta, triplerailLightblue, triplerailYellow, triplerailLime, triplerailPink, triplerailGray, triplerailLightgray, triplerailCyan, triplerailPurple, triplerailBlue, triplerailBrown, triplerailGreen, triplerailRed, triplerailBlack;
    public static Block triplerailDiamond, triplerailGlowing, triplerailGrayOrange, triplerailNether, triplerailObsidian, triplerailRedGreen, triplerailYellowBlue, triplerailEmerald, triplerailLapis, triplerailPowered, triplerailIce, triplerailChain, triplerailArmed, triplerailEnderPearl;
    public static Item minecartWhite, minecartOrange, minecartMagenta, minecartLightblue, minecartYellow, minecartLime, minecartPink, minecartGray, minecartLightgray, minecartCyan, minecartPurple, minecartBlue, minecartBrown, minecartGreen, minecartRed, minecartBlack;
    public static Item emeraldBar, diamondBar, obsidianBar, lapisBar, explosiveBar, ironNail, goldNail, diamondNail, emeraldNail, obsidianNail, netherrackNail, woolenNail, netherIngot, railIronBase, railDiamondBase, railObsidianBase, railNetherrackBase, railEmeraldBase, railLapisBase, railGoldBase, railArmedBase, railChainBase, railIceBase, railEnderPearlBase, obsidianChunk;
    private GuiHandlerRailsCraftingTable guiHandlerRailsCraftingTable = new GuiHandlerRailsCraftingTable();

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        net.minecraftforge.common.config.Configuration config = new net.minecraftforge.common.config.Configuration(event.getSuggestedConfigurationFile());
        config.load();
        net.minecraftforge.common.config.Property blockProperty = config.get(net.minecraftforge.common.config.Configuration.CATEGORY_GENERAL, "A:BlockConfigString", "null");
        blockProperty.comment = "Here you can change the IDs of the Mod's Blocks to your preference. Block ID must NOT extend over 4095!";
        obsidianRailID = config.get("block", "ObsidianRail", 3001).getInt();
        diamondRailID = config.get("block", "DiamondRail", 3002).getInt();
        lapisRailID = config.get("block", "LapisRail", 3003).getInt();
        iceRailID = config.get("block", "IceRail", 3004).getInt();
        glowstoneRailID = config.get("block", "GlowstoneRail", 3005).getInt();
        diamondNetherRailID = config.get("block", "DiamondNetherRail", 3006).getInt();
        diamondObsidianRailID = config.get("block", "DiamondObsidianRail", 3007).getInt();
        brickRailID = config.get("block", "BrickRail", 3008).getInt();
        emeraldRailID = config.get("block", "EmeraldRail", 3009).getInt();
        netherStarRailID = config.get("block", "NetherStarRail", 3010).getInt();
        enderPearlRailID = config.get("block", "EnderPearlRail", 3011).getInt();
        chainRailID = config.get("block", "ChainRail", 3012).getInt();
        armedRailID = config.get("block", "ArmedRail", 3013).getInt();
        whiteWoolRailID = config.get("block", "WhiteWoolRail", 3081).getInt();
        orangeWoolRailID = config.get("block", "OrangeWoolRail", 3082).getInt();
        magentaWoolRailID = config.get("block", "MagentaWoolRail", 3083).getInt();
        lightblueWoolRailID = config.get("block", "LightBlueWoolRail", 3084).getInt();
        yellowWoolRailID = config.get("block", "YellowWoolRail", 3085).getInt();
        limeWoolRailID = config.get("block", "LimeWoolRail", 3086).getInt();
        pinkWoolRailID = config.get("block", "PinkWoolRail", 3087).getInt();
        grayWoolRailID = config.get("block", "GrayWoolRail", 3088).getInt();
        lightgrayWoolRailID = config.get("block", "LightgrayWoolRail", 3089).getInt();
        cyanWoolRailID = config.get("block", "CyanWoolRail", 3090).getInt();
        purpleWoolRailID = config.get("block", "PurpleWoolRail", 3091).getInt();
        blueWoolRailID = config.get("block", "BlueWoolRail", 3092).getInt();
        brownWoolRailID = config.get("block", "BrownWoolRail", 3093).getInt();
        greenWoolRailID = config.get("block", "GreenWoolRail", 3094).getInt();
        redWoolRailID = config.get("block", "RedWoolRail", 3095).getInt();
        blackWoolRailID = config.get("block", "BlackWoolRail", 3096).getInt();
        railsCraftingTableID = config.get("block", "RailsCraftingTable", 2901).getInt();
//    	railBrakeID = config.get("block", "TileEntityRailBrake",3055).getInt();
        monorailDiamondID = config.get("block", "MonorailDiamond", 3128).getInt();
        monorailGlowingID = config.get("block", "MonorailGlowing", 3130).getInt();
        monorailGrayOrangeID = config.get("block", "TriplerailGrayOrange", 3136).getInt();
        monorailNetherID = config.get("block", "MonorailNether", 3131).getInt();
        monorailObsidianID = config.get("block", "MonorailObsidian", 3129).getInt();
        monorailRedGreenID = config.get("block", "MonorailRedGreen", 3134).getInt();
        monorailYellowBlueID = config.get("block", "MonorailYellowBlue", 3135).getInt();
        monorailEmeraldID = config.get("block", "MonorailEmerald", 3132).getInt();
        monorailLapisID = config.get("block", "MonorailLapis", 3133).getInt();
        monorailGoldID = config.get("block", "MonorailGold", 3137).getInt();
        monorailPoweredID = config.get("block", "MonorailPowered", 3138).getInt();
        monorailIceID = config.get("block", "MonorailIce", 3139).getInt();
        monorailChainID = config.get("block", "MonorailChain", 3140).getInt();
        monorailArmedID = config.get("block", "MonorailArmed", 3141).getInt();
        monorailEnderPearlID = config.get("block", "MonorailEnderPearl", 3142).getInt();
        monorailWhiteID = config.get("block", "MonorailWhite", 3169).getInt();
        monorailOrangeID = config.get("block", "MonorailOrange", 3170).getInt();
        monorailMagentaID = config.get("block", "MonorailMagenta", 3171).getInt();
        monorailLightblueID = config.get("block", "MonorailLightblue", 3172).getInt();
        monorailYellowID = config.get("block", "MonorailYellow", 3173).getInt();
        monorailLimeID = config.get("block", "MonorailLime", 3174).getInt();
        monorailPinkID = config.get("block", "MonorailPink", 3175).getInt();
        monorailGrayID = config.get("block", "MonorailGray", 3176).getInt();
        monorailLightgrayID = config.get("block", "MonorailLightgray", 3177).getInt();
        monorailCyanID = config.get("block", "MonorailCyan", 3178).getInt();
        monorailPurpleID = config.get("block", "MonorailPurple", 3179).getInt();
        monorailBlueID = config.get("block", "MonorailBlue", 3180).getInt();
        monorailBrownID = config.get("block", "MonorailBrown", 3181).getInt();
        monorailGreenID = config.get("block", "MonorailGreen", 3182).getInt();
        monorailRedID = config.get("block", "MonorailRed", 3183).getInt();
        monorailBlackID = config.get("block", "MonorailBlack", 3184).getInt();
        //Triplerails//
        triplerailDiamondID = config.get("block", "TriplerailDiamond", 3185).getInt();
        triplerailGlowingID = config.get("block", "TriplerailGlowing", 3186).getInt();
        triplerailNetherID = config.get("block", "TriplerailNether", 3187).getInt();
        triplerailObsidianID = config.get("block", "TriplerailObsidian", 3188).getInt();
        triplerailEmeraldID = config.get("block", "TriplerailEmerald", 3189).getInt();
        triplerailLapisID = config.get("block", "TriplerailLapis", 3190).getInt();
        triplerailPoweredID = config.get("block", "TriplerailPowered", 3192).getInt();
        triplerailIceID = config.get("block", "TriplerailIce", 3193).getInt();
        triplerailChainID = config.get("block", "TriplerailChain", 3194).getInt();
        triplerailArmedID = config.get("block", "TriplerailArmed", 3195).getInt();
        triplerailEnderPearlID = config.get("block", "TriplerailEnderPearl", 3196).getInt();
        triplerailWhiteID = config.get("block", "TriplerailWhite", 3197).getInt();
        triplerailOrangeID = config.get("block", "TriplerailOrange", 3198).getInt();
        triplerailMagentaID = config.get("block", "TriplerailMagenta", 3199).getInt();
        triplerailLightblueID = config.get("block", "TriplerailLightblue", 3200).getInt();
        triplerailYellowID = config.get("block", "TriplerailYellow", 3201).getInt();
        triplerailLimeID = config.get("block", "TriplerailLime", 3202).getInt();
        triplerailPinkID = config.get("block", "TriplerailPink", 3203).getInt();
        triplerailGrayID = config.get("block", "TriplerailGray", 3204).getInt();
        triplerailLightgrayID = config.get("block", "TriplerailLightgray", 3205).getInt();
        triplerailCyanID = config.get("block", "TriplerailCyan", 3206).getInt();
        triplerailPurpleID = config.get("block", "TriplerailPurple", 3207).getInt();
        triplerailBlueID = config.get("block", "TriplerailBlue", 3208).getInt();
        triplerailBrownID = config.get("block", "TriplerailBrown", 3209).getInt();
        triplerailGreenID = config.get("block", "TriplerailGreen", 3210).getInt();
        triplerailRedID = config.get("block", "TriplerailRed", 3211).getInt();
        triplerailBlackID = config.get("block", "TriplerailBlack", 3212).getInt();
        net.minecraftforge.common.config.Property itemProperty = config.get(net.minecraftforge.common.config.Configuration.CATEGORY_GENERAL, "A:ItemConfigString", "null");
        itemProperty.comment = "Here you can change the IDs of the Mod's Items to your preference. Due to Minecraft's code, the item IDs often get shifted by 256 up or down. If your item ID is 4000, in-game it would be either 3744, 4000 or 4256.";
        obsidianChunkID = config.get("item", "obsidianChunk", 7999).getInt();
        diamondBarID = config.get("item", "diamondBar", 8000).getInt();
        emeraldBarID = config.get("item", "emeraldBar", 8001).getInt();
        obsidianBarID = config.get("item", "obsidianBar", 8002).getInt();
        lapisBarID = config.get("item", "lapisBar", 8003).getInt();
        explosiveBarID = config.get("item", "explosiveBar", 8004).getInt();
        ironNailID = config.get("item", "ironNail", 8024).getInt();
        goldNailID = config.get("item", "goldNail", 8025).getInt();
        diamondNailID = config.get("item", "diamondNail", 8026).getInt();
        emeraldNailID = config.get("item", "emeraldNail", 8027).getInt();
        obsidianNailID = config.get("item", "obsidianNail", 8028).getInt();
        netherrackNailID = config.get("item", "netherrackNail", 8029).getInt();
        woolenNailID = config.get("item", "woolenNail", 8030).getInt();
        netherIngotID = config.get("item", "netherIngot", 8051).getInt();
        railIronBaseID = config.get("item", "railIronBase", 8062).getInt();
        railDiamondBaseID = config.get("item", "railDiamondBase", 8063).getInt();
        railObsidianBaseID = config.get("item", "railObsidianBase", 8064).getInt();
        railNetherrackBaseID = config.get("item", "railNetherrackBase", 8065).getInt();
        railEmeraldBaseID = config.get("item", "railEmeraldBase", 8066).getInt();
        railLapisBaseID = config.get("item", "railLapisBase", 8067).getInt();
        railGoldBaseID = config.get("item", "railGoldBase", 8068).getInt();
        railArmedBaseID = config.get("item", "railArmedBase", 8069).getInt();
        railChainBaseID = config.get("item", "railChainBase", 8070).getInt();
        railIceBaseID = config.get("item", "railIceBase", 8071).getInt();
        railEnderPearlBaseID = config.get("item", "railEnderPearlBase", 8072).getInt();
        //minecartWhiteID = config.get("item", "minecartWhite", 8073).getInt();
        //minecartOrangeID = config.get("item", "minecartOrange", 8074).getInt();
        //minecartMagentaID = config.get("item", "minecartMagenta", 8075).getInt();
        //minecartLightblueID = config.get("item", "minecartLightblue", 8076).getInt();
        //minecartYellowID = config.get("item", "minecartYellow", 8077).getInt();
        //minecartLimeID = config.get("item", "minecartLime", 8078).getInt();
        //minecartPinkID = config.get("item", "minecartPink", 8079).getInt();
        //minecartGrayID = config.get("item", "minecartGray", 8080).getInt();
        //minecartLightgrayID = config.get("item", "minecartLightgray", 8081).getInt();
        //minecartCyanID = config.get("item", "minecartCyan", 8082).getInt();
        //minecartPurpleID = config.get("item", "minecartPurple", 8083).getInt();
        //minecartBlueID = config.get("item", "minecartBlue", 8084).getInt();
        //minecartBrownID = config.get("item", "minecartBrown", 8085).getInt();
        //minecartGreenID = config.get("item", "minecartGreen", 8086).getInt();
        //minecartRedID = config.get("item", "minecartRed", 8087).getInt();
        //minecartBlackID = config.get("item", "minecartBlack", 8088).getInt();
        config.save();
    }

    @EventHandler
    public void load(FMLInitializationEvent event)
    {
        //Custom Blocks//
        obsidianRail = new ObsidianRail(obsidianRailID).setBlockName("obsidianRail");
        diamondRail = new DiamondRail(diamondRailID).setBlockName("diamondRail");
        lapisRail = new LapisRail(lapisRailID).setBlockName("lapisRail");
        iceRail = new IceRail(iceRailID).setBlockName("iceRail");
        glowstoneRail = new GlowstoneRail(glowstoneRailID).setBlockName("glowstoneRail");
        diamondNetherRail = new DiamondNetherRail(diamondNetherRailID).setBlockName("diamondNetherRail");
        diamondObsidianRail = new DiamondObsidianRail(diamondObsidianRailID).setBlockName("diamondObsidianRail");
        brickRail = new AllRails(brickRailID).setBlockName("brickRail").setBlockTextureName("expandedrails:BrickRail");
        emeraldRail = new EmeraldRail(emeraldRailID).setBlockName("emeraldRail");
        netherStarRail = new AllRails(netherStarRailID).setBlockName("netherStarRail").setBlockTextureName("expandedrails:NetherStarRail");
        enderPearlRail = new EnderPearlRail(enderPearlRailID).setBlockName("enderPearlRail");
        chainRail = new ChainRail(chainRailID).setBlockName("chainRail");
        armedRail = new ArmedRail(armedRailID).setBlockName("armedRail");
        railsCraftingTable = new RailsCraftingTable(railsCraftingTableID).setBlockName("railsCraftingTable");
        //railBrake = new TileEntityRailBrake(railBrakeID, Material.rock).setBlockName("railBrake");
        monorailDiamond = new MonorailDiamond(monorailDiamondID).setBlockName("monorailDiamond");
        monorailGlowing = new MonorailGlowing(monorailGlowingID).setBlockName("monorailGlowing");
        monorailGrayOrange = new AllRails(monorailGrayOrangeID).setBlockName("monorailGrayOrange").setBlockTextureName("expandedrails:GrayOrangeMonorail");
        monorailNether = new AllRails(monorailNetherID).setBlockName("monorailNether").setBlockTextureName("expandedrails:NetherMonorail");
        monorailObsidian = new MonorailObsidian(monorailObsidianID).setBlockName("monorailObsidian");
        monorailRedGreen = new AllRails(monorailRedGreenID).setBlockName("monorailRedGreen").setBlockTextureName("expandedrails:RedGreenMonorail");
        monorailYellowBlue = new AllRails(monorailYellowBlueID).setBlockName("monorailYellowBlue").setBlockTextureName("expandedrails:YellowBlueMonorail");
        monorailEmerald = new MonorailEmerald(monorailEmeraldID).setBlockName("monorailEmerald");
        monorailLapis = new MonorailLapis(monorailLapisID).setBlockName("monorailLapis");
        monorailGold = new AllRails(monorailGoldID).setBlockName("monorailGold").setBlockTextureName("expandedrails:GoldMonorail");
        monorailPowered = new MonorailPowered(monorailPoweredID).setBlockName("monorailPowered");
        monorailIce = new MonorailIce(monorailIceID).setBlockName("monorailIce");
        monorailChain = new MonorailChain(monorailChainID).setBlockName("monorailChain");
        monorailArmed = new MonorailArmed(monorailArmedID).setBlockName("monorailArmed");
        monorailEnderPearl = new MonorailEnderPearl(monorailEnderPearlID).setBlockName("monorailEnderPearl");
        //Triplerail//
        triplerailDiamond = new TriplerailDiamond(triplerailDiamondID).setBlockName("triplerailDiamond").setBlockTextureName("expandedrails:DiamondTriplerail");
        triplerailGlowing = new TriplerailGlowing(triplerailGlowingID).setBlockName("triplerailGlowing").setBlockTextureName("expandedrails:GlowTriplerail");
        triplerailNether = new AllRails(triplerailNetherID).setBlockName("triplerailNether").setBlockTextureName("expandedrails:NetherTriplerail");
        triplerailObsidian = new AllRails(triplerailObsidianID).setBlockName("triplerailObsidian").setBlockTextureName("expandedrails:ObsidianTriplerail");
        triplerailEmerald = new TriplerailEmerald(triplerailEmeraldID).setBlockName("triplerailEmerald").setBlockTextureName("expandedrails:EmeraldTriplerail");
        triplerailLapis = new TriplerailLapis(triplerailLapisID).setBlockName("triplerailLapis").setBlockTextureName("expandedrails:LapisTriplerail");
        triplerailPowered = new TriplerailPowered(triplerailPoweredID).setBlockName("triplerailPowered").setBlockTextureName("expandedrails:TriplerailPowered");
        triplerailIce = new TriplerailIce(triplerailIceID).setBlockName("triplerailIce").setBlockTextureName("expandedrails:IceTriplerail");
        triplerailChain = new TriplerailChain(triplerailChainID).setBlockName("triplerailChain").setBlockTextureName("expandedrails:ChainTriplerail");
        triplerailArmed = new TriplerailArmed(triplerailArmedID).setBlockName("triplerailArmed").setBlockTextureName("expandedrails:ArmedTriplerail");
        triplerailEnderPearl = new TriplerailEnderPearl(triplerailEnderPearlID).setBlockName("triplerailEnderPearl").setBlockTextureName("expandedrails:EnderPearlTriplerail");
        //Wool Rails//
        whiteWoolRail = new AllRails(whiteWoolRailID).setBlockName("whiteWoolRail").setBlockTextureName("expandedrails:WhiteWoolRail");
        orangeWoolRail = new AllRails(orangeWoolRailID).setBlockName("orangeWoolRail").setBlockTextureName("expandedrails:OrangeWoolRail");
        magentaWoolRail = new AllRails(magentaWoolRailID).setBlockName("magentaWoolRail").setBlockTextureName("expandedrails:MagentaWoolRail");
        lightblueWoolRail = new AllRails(lightblueWoolRailID).setBlockName("lightblueWoolRail").setBlockTextureName("expandedrails:LightBlueWoolRail");
        yellowWoolRail = new AllRails(yellowWoolRailID).setBlockName("yellowWoolRail").setBlockTextureName("expandedrails:YellowWoolRail");
        limeWoolRail = new AllRails(limeWoolRailID).setBlockName("limeWoolRail").setBlockTextureName("expandedrails:LimeWoolRail");
        pinkWoolRail = new AllRails(pinkWoolRailID).setBlockName("pinkWoolRail").setBlockTextureName("expandedrails:PinkWoolRail");
        grayWoolRail = new AllRails(grayWoolRailID).setBlockName("grayWoolRail").setBlockTextureName("expandedrails:GrayWoolRail");
        lightgrayWoolRail = new AllRails(lightgrayWoolRailID).setBlockName("lightgrayWoolRail").setBlockTextureName("expandedrails:LightGrayWoolRail");
        cyanWoolRail = new AllRails(cyanWoolRailID).setBlockName("cyanWoolRail").setBlockTextureName("expandedrails:CyanWoolRail");
        purpleWoolRail = new AllRails(purpleWoolRailID).setBlockName("purpleWoolRail").setBlockTextureName("expandedrails:PurpleWoolRail");
        blueWoolRail = new AllRails(blueWoolRailID).setBlockName("blueWoolRail").setBlockTextureName("expandedrails:BlueWoolRail");
        brownWoolRail = new AllRails(brownWoolRailID).setBlockName("brownWoolRail").setBlockTextureName("expandedrails:BrownWoolRail");
        greenWoolRail = new AllRails(greenWoolRailID).setBlockName("greenWoolRail").setBlockTextureName("expandedrails:GreenWoolRail");
        redWoolRail = new AllRails(redWoolRailID).setBlockName("redWoolRail").setBlockTextureName("expandedrails:RedWoolRail");
        blackWoolRail = new AllRails(blackWoolRailID).setBlockName("blackWoolRail").setBlockTextureName("expandedrails:BlackWoolRail");
        //Wool Monorails//
        monorailWhite = new AllRails(monorailWhiteID).setBlockName("monorailWhite").setBlockTextureName("expandedrails:MonorailWhite");
        monorailOrange = new AllRails(monorailOrangeID).setBlockName("monorailOrange").setBlockTextureName("expandedrails:MonorailOrange");
        monorailMagenta = new AllRails(monorailMagentaID).setBlockName("monorailMagenta").setBlockTextureName("expandedrails:MonorailMagenta");
        monorailLightblue = new AllRails(monorailLightblueID).setBlockName("monorailLightblue").setBlockTextureName("expandedrails:MonorailLightBlue");
        monorailYellow = new AllRails(monorailYellowID).setBlockName("monorailYellow").setBlockTextureName("expandedrails:MonorailYellow");
        monorailLime = new AllRails(monorailLimeID).setBlockName("monorailLime").setBlockTextureName("expandedrails:MonorailLime");
        monorailPink = new AllRails(monorailPinkID).setBlockName("monorailPink").setBlockTextureName("expandedrails:MonorailPink");
        monorailGray = new AllRails(monorailGrayID).setBlockName("monorailGray").setBlockTextureName("expandedrails:MonorailGray");
        monorailLightgray = new AllRails(monorailLightgrayID).setBlockName("monorailLightgray").setBlockTextureName("expandedrails:MonorailLightGray");
        monorailCyan = new AllRails(monorailCyanID).setBlockName("monorailCyan").setBlockTextureName("expandedrails:MonorailCyan");
        monorailPurple = new AllRails(monorailPurpleID).setBlockName("monorailPurple").setBlockTextureName("expandedrails:MonorailPurple");
        monorailBlue = new AllRails(monorailBlueID).setBlockName("monorailBlue").setBlockTextureName("expandedrails:MonorailBlue");
        monorailBrown = new AllRails(monorailBrownID).setBlockName("monorailBrown").setBlockTextureName("expandedrails:MonorailBrown");
        monorailGreen = new AllRails(monorailGreenID).setBlockName("monorailGreen").setBlockTextureName("expandedrails:MonorailGreen");
        monorailRed = new AllRails(monorailRedID).setBlockName("monorailRed").setBlockTextureName("expandedrails:MonorailRed");
        monorailBlack = new AllRails(monorailBlackID).setBlockName("monorailBlack").setBlockTextureName("expandedrails:MonorailBlack");
        //Wool Triplerails//
        triplerailWhite = new AllRails(triplerailWhiteID).setBlockName("triplerailWhite").setBlockTextureName("expandedrails:TriplerailWhite");
        triplerailOrange = new AllRails(triplerailOrangeID).setBlockName("triplerailOrange").setBlockTextureName("expandedrails:TriplerailOrange");
        triplerailMagenta = new AllRails(triplerailMagentaID).setBlockName("triplerailMagenta").setBlockTextureName("expandedrails:TriplerailMagenta");
        triplerailLightblue = new AllRails(triplerailLightblueID).setBlockName("triplerailLightblue").setBlockTextureName("expandedrails:TriplerailLightBlue");
        triplerailYellow = new AllRails(triplerailYellowID).setBlockName("triplerailYellow").setBlockTextureName("expandedrails:TriplerailYellow");
        triplerailLime = new AllRails(triplerailLimeID).setBlockName("triplerailLime").setBlockTextureName("expandedrails:TriplerailLime");
        triplerailPink = new AllRails(triplerailPinkID).setBlockName("triplerailPink").setBlockTextureName("expandedrails:TriplerailPink");
        triplerailGray = new AllRails(triplerailGrayID).setBlockName("triplerailGray").setBlockTextureName("expandedrails:TriplerailGray");
        triplerailLightgray = new AllRails(triplerailLightgrayID).setBlockName("triplerailLightgray").setBlockTextureName("expandedrails:TriplerailLightGray");
        triplerailCyan = new AllRails(triplerailCyanID).setBlockName("triplerailCyan").setBlockTextureName("expandedrails:TriplerailCyan");
        triplerailPurple = new AllRails(triplerailPurpleID).setBlockName("triplerailPurple").setBlockTextureName("expandedrails:TriplerailPurple");
        triplerailBlue = new AllRails(triplerailBlueID).setBlockName("triplerailBlue").setBlockTextureName("expandedrails:TriplerailBlue");
        triplerailBrown = new AllRails(triplerailBrownID).setBlockName("triplerailBrown").setBlockTextureName("expandedrails:TriplerailBrown");
        triplerailGreen = new AllRails(triplerailGreenID).setBlockName("triplerailGreen").setBlockTextureName("expandedrails:TriplerailGreen");
        triplerailRed = new AllRails(triplerailRedID).setBlockName("triplerailRed").setBlockTextureName("expandedrails:TriplerailRed");
        triplerailBlack = new AllRails(triplerailBlackID).setBlockName("triplerailBlack").setBlockTextureName("expandedrails:TriplerailBlack");
        //Custom Items//
        emeraldBar = new ExpandedItem(emeraldBarID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("emeraldBar").setTextureName("expandedrails:EmeraldBar");
        diamondBar = new ExpandedItem(diamondBarID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("diamondBar").setTextureName("expandedrails:DiamondBar");
        obsidianBar = new ExpandedItem(obsidianBarID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("obsidianBar").setTextureName("expandedrails:ObsidianBar");
        lapisBar = new ExpandedItem(lapisBarID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("lapisBar").setTextureName("expandedrails:LapisBar");
        explosiveBar = new ExpandedItem(explosiveBarID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("explosiveBar").setTextureName("expandedrails:ExplosiveBar");
        ironNail = new ExpandedItem(ironNailID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("ironNail").setTextureName("expandedrails:Nail_Iron");
        goldNail = new ExpandedItem(goldNailID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("goldNail").setTextureName("expandedrails:Nail_Gold");
        diamondNail = new ExpandedItem(diamondNailID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("diamondNail").setTextureName("expandedrails:Nail_Diamond");
        emeraldNail = new ExpandedItem(emeraldNailID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("emeraldNail").setTextureName("expandedrails:Nail_Emerald");
        obsidianNail = new ExpandedItem(obsidianNailID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("obsidianNail").setTextureName("expandedrails:Nail_Obsidian");
        netherrackNail = new ExpandedItem(netherrackNailID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("netherrackNail").setTextureName("expandedrails:Nail_Nether");
        woolenNail = new ExpandedItem(woolenNailID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("woolenNail").setTextureName("expandedrails:Nail_Woolen");
        netherIngot = new ExpandedItem(netherIngotID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("netherIngot").setTextureName("expandedrails:Nether_Ingot");
        railIronBase = new ExpandedItem(railIronBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railIronBase").setTextureName("expandedrails:Rail_Iron_Base");
        railDiamondBase = new ExpandedItem(railDiamondBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railDiamondBase").setTextureName("expandedrails:Rail_Diamond_Base");
        railObsidianBase = new ExpandedItem(railObsidianBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railObsidianBase").setTextureName("expandedrails:Rail_Obsidian_Base");
        railNetherrackBase = new ExpandedItem(railNetherrackBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railNetherrackBase").setTextureName("expandedrails:Rail_Nether_Base");
        railEmeraldBase = new ExpandedItem(railEmeraldBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railEmeraldBase").setTextureName("expandedrails:Rail_Emerald_Base");
        railLapisBase = new ExpandedItem(railLapisBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railLapisBase").setTextureName("expandedrails:Rail_Lapis_Base");
        railGoldBase = new ExpandedItem(railGoldBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railGoldBase").setTextureName("expandedrails:Rail_Gold_Base");
        railArmedBase = new ExpandedItem(railArmedBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railArmedBase").setTextureName("expandedrails:Rail_Armed_Base");
        railChainBase = new ExpandedItem(railChainBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railChainBase").setTextureName("expandedrails:Rail_Chain_Base");
        railIceBase = new ExpandedItem(railIceBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railIceBase").setTextureName("expandedrails:Rail_Ice_Base");
        railEnderPearlBase = new ExpandedItem(railEnderPearlBaseID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("railEnderPearlBase").setTextureName("expandedrails:Rail_EnderPearl_Base");
        obsidianChunk = new ExpandedItem(obsidianChunkID).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("obsidianChunk").setTextureName("expandedrails:ObsidianChunk");
        //minecartWhite = new ExpandedItem(minecartWhiteID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartWhite").setTextureName("expandedrails:MinecartWhite");
        //minecartOrange = new ExpandedItem(minecartOrangeID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartOrange").setTextureName("expandedrails:MinecartOrange");
        //minecartMagenta = new ExpandedItem(minecartMagentaID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartMagenta").setTextureName("expandedrails:MinecartMagenta");
        //minecartLightblue = new ExpandedItem(minecartLightblueID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartLightblue").setTextureName("expandedrails:MinecartLightblue");
        //minecartYellow = new ExpandedItem(minecartYellowID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartYellow").setTextureName("expandedrails:MinecartYellow");
        //minecartLime = new ExpandedItem(minecartLimeID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartLime").setTextureName("expandedrails:MinecartLime");
        //minecartPink = new ExpandedItem(minecartPinkID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartPink").setTextureName("expandedrails:MinecartPink");
        //minecartGray = new ExpandedItem(minecartGrayID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartGray").setTextureName("expandedrails:MinecartGray");
        //minecartLightgray = new ExpandedItem(minecartLightgrayID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartLightgray").setTextureName("expandedrails:MinecartLightgray");
        //minecartCyan = new ExpandedItem(minecartCyanID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartCyan").setTextureName("expandedrails:MinecartCyan");
        //minecartPurple = new ExpandedItem(minecartPurpleID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartPurple").setTextureName("expandedrails:MinecartPurple");
        //minecartBlue = new ExpandedItem(minecartBlueID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartBlue").setTextureName("expandedrails:MinecartBlue");
        //minecartBrown = new ExpandedItem(minecartBrownID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartBrown").setTextureName("expandedrails:MinecartBrown");
        //minecartGreen = new ExpandedItem(minecartGreenID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartGreen").setTextureName("expandedrails:MinecartGreen");
        //minecartRed = new ExpandedItem(minecartRedID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartRed").setTextureName("expandedrails:MinecartRed");
        //minecartBlack = new ExpandedItem(minecartBlackID).setCreativeTab(CreativeTabs.tabTransport).setUnlocalizedName("minecartBlack").setTextureName("expandedrails:MinecartBlack");
        //Block Registering//
        LanguageRegistry.addName(obsidianRail, "Obsidian Rail");
        //MinecraftForge.setBlockHarvestLevel(obsidianRail, "pickaxe", 0);
        GameRegistry.registerBlock(obsidianRail, "obsidianRail");
        LanguageRegistry.addName(lapisRail, "Lapis Lazuli Rail");
        //MinecraftForge.setBlockHarvestLevel(lapisRail, "pickaxe", 0);
        GameRegistry.registerBlock(lapisRail, "lapisRail");
        LanguageRegistry.addName(diamondRail, "Diamond Rail");
        //MinecraftForge.setBlockHarvestLevel(diamondRail, "pickaxe", 0);
        GameRegistry.registerBlock(diamondRail, "diamondRail");
        LanguageRegistry.addName(diamondNetherRail, "Diamond-Nether Rail");
        //MinecraftForge.setBlockHarvestLevel(diamondNetherRail, "pickaxe", 0);
        GameRegistry.registerBlock(diamondNetherRail, "diamondNetherRail");
        LanguageRegistry.addName(diamondObsidianRail, "Diamond-Obsidian Rail");
        //MinecraftForge.setBlockHarvestLevel(diamondObsidianRail, "pickaxe", 0);
        GameRegistry.registerBlock(diamondObsidianRail, "diamondoORail");
        LanguageRegistry.addName(iceRail, "Ice Rail");
        //MinecraftForge.setBlockHarvestLevel(iceRail, "pickaxe", 0);
        GameRegistry.registerBlock(iceRail, "iceRail");
        LanguageRegistry.addName(glowstoneRail, "Glowing Rail");
        //MinecraftForge.setBlockHarvestLevel(glowstoneRail, "pickaxe", 0);
        GameRegistry.registerBlock(glowstoneRail, "glowstoneRail");
        LanguageRegistry.addName(whiteWoolRail, "White Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(whiteWoolRail, "pickaxe", 2);
        GameRegistry.registerBlock(whiteWoolRail, "whiteWoolRail");
        LanguageRegistry.addName(orangeWoolRail, "Orange Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(orangeWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(orangeWoolRail, "orangeWoolRail");
        LanguageRegistry.addName(magentaWoolRail, "Magenta Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(magentaWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(magentaWoolRail, "magentaWoolRail");
        LanguageRegistry.addName(lightblueWoolRail, "LightBlue Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(lightblueWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(lightblueWoolRail, "lightblueWoolRail");
        LanguageRegistry.addName(yellowWoolRail, "Yellow Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(yellowWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(yellowWoolRail, "yellowWoolRail");
        LanguageRegistry.addName(limeWoolRail, "Lime Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(limeWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(limeWoolRail, "limeWoolRail");
        LanguageRegistry.addName(pinkWoolRail, "Pink Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(pinkWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(pinkWoolRail, "pinkWoolRail");
        LanguageRegistry.addName(grayWoolRail, "Gray Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(grayWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(grayWoolRail, "grayWoolRail");
        LanguageRegistry.addName(lightgrayWoolRail, "LightGray Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(lightgrayWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(lightgrayWoolRail, "lightgrayWoolRail");
        LanguageRegistry.addName(cyanWoolRail, "Cyan Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(cyanWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(cyanWoolRail, "cyanWoolRail");
        LanguageRegistry.addName(purpleWoolRail, "Purple Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(purpleWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(purpleWoolRail, "purpleWoolRail");
        LanguageRegistry.addName(blueWoolRail, "Blue Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(blueWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(blueWoolRail, "blueWoolRail");
        LanguageRegistry.addName(brownWoolRail, "Brown Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(brownWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(brownWoolRail, "brownWoolRail");
        LanguageRegistry.addName(greenWoolRail, "Green Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(greenWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(greenWoolRail, "greenWoolRail");
        LanguageRegistry.addName(redWoolRail, "Red Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(redWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(redWoolRail, "redWoolRail");
        LanguageRegistry.addName(blackWoolRail, "Black Wool Rail");
        //MinecraftForge.setBlockHarvestLevel(blackWoolRail, "pickaxe", 0);
        GameRegistry.registerBlock(blackWoolRail, "blackWoolRail");
        LanguageRegistry.addName(brickRail, "Brick Rail");
        //MinecraftForge.setBlockHarvestLevel(brickRail, "pickaxe", 0);
        GameRegistry.registerBlock(brickRail, "brickRail");
        LanguageRegistry.addName(netherStarRail, "NetherStar Rail");
        //MinecraftForge.setBlockHarvestLevel(netherStarRail, "pickaxe", 0);
        GameRegistry.registerBlock(netherStarRail, "netherStarRail");
        LanguageRegistry.addName(emeraldRail, "Emerald Rail");
        //MinecraftForge.setBlockHarvestLevel(emeraldRail, "pickaxe", 0);
        GameRegistry.registerBlock(emeraldRail, "emeraldRail");
        LanguageRegistry.addName(enderPearlRail, "EnderPearl Rail");
        //MinecraftForge.setBlockHarvestLevel(enderPearlRail, "pickaxe", 0);
        GameRegistry.registerBlock(enderPearlRail, "enderPearlRail");
        LanguageRegistry.addName(chainRail, "Chain Rail");
        //MinecraftForge.setBlockHarvestLevel(chainRail, "pickaxe", 0);
        GameRegistry.registerBlock(chainRail, "chainRail");
        LanguageRegistry.addName(armedRail, "Armed Rail");
        //MinecraftForge.setBlockHarvestLevel(armedRail, "pickaxe", 0);
        GameRegistry.registerBlock(armedRail, "armedRail");
        //Monorail//
        LanguageRegistry.addName(monorailDiamond, "Diamond Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailDiamond, "pickaxe", 0);
        GameRegistry.registerBlock(monorailDiamond, "monorailDiamond");
        LanguageRegistry.addName(monorailGlowing, "Glowing Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailGlowing, "pickaxe", 0);
        GameRegistry.registerBlock(monorailGlowing, "monorailGlowing");
        LanguageRegistry.addName(monorailGrayOrange, "Gray-Orange Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailGrayOrange, "pickaxe", 0);
        GameRegistry.registerBlock(monorailGrayOrange, "monorailGrayOrange");
        LanguageRegistry.addName(monorailNether, "Nether Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailNether, "pickaxe", 0);
        GameRegistry.registerBlock(monorailNether, "monorailNether");
        LanguageRegistry.addName(monorailObsidian, "Obsidian Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailObsidian, "pickaxe", 0);
        GameRegistry.registerBlock(monorailObsidian, "monorailObsidian");
        LanguageRegistry.addName(monorailRedGreen, "Red-Green Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailRedGreen, "pickaxe", 0);
        GameRegistry.registerBlock(monorailRedGreen, "monorailRedGreen");
        LanguageRegistry.addName(monorailYellowBlue, "Yellow-Blue Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailYellowBlue, "pickaxe", 0);
        GameRegistry.registerBlock(monorailYellowBlue, "monorailYellowBlue");
        LanguageRegistry.addName(monorailEmerald, "Emerald Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailEmerald, "pickaxe", 0);
        GameRegistry.registerBlock(monorailEmerald, "monorailEmerald");
        LanguageRegistry.addName(monorailLapis, "Lapis Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailLapis, "pickaxe", 0);
        GameRegistry.registerBlock(monorailLapis, "monorailLapis");
        LanguageRegistry.addName(monorailGold, "Gold Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailGold, "pickaxe", 0);
        GameRegistry.registerBlock(monorailGold, "monorailGold");
        LanguageRegistry.addName(monorailPowered, "Powered Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailPowered, "pickaxe", 0);
        GameRegistry.registerBlock(monorailPowered, "monorailPowered");
        LanguageRegistry.addName(monorailIce, "Ice Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailIce, "pickaxe", 0);
        GameRegistry.registerBlock(monorailIce, "monorailIce");
        LanguageRegistry.addName(monorailChain, "Chain Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailChain, "pickaxe", 0);
        GameRegistry.registerBlock(monorailChain, "monorailChain");
        LanguageRegistry.addName(monorailArmed, "Armed Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailArmed, "pickaxe", 0);
        GameRegistry.registerBlock(monorailArmed, "monorailArmed");
        LanguageRegistry.addName(monorailEnderPearl, "Ender Pearl Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailEnderPearl, "pickaxe", 0);
        GameRegistry.registerBlock(monorailEnderPearl, "monorailEnderPearl");
        //Mono Wool Rails//
        LanguageRegistry.addName(monorailWhite, "White Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailWhite, "pickaxe", 0);
        GameRegistry.registerBlock(monorailWhite, "monorailWhite");
        LanguageRegistry.addName(monorailOrange, "Orange Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailOrange, "pickaxe", 0);
        GameRegistry.registerBlock(monorailOrange, "monorailOrange");
        LanguageRegistry.addName(monorailMagenta, "Magenta Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailMagenta, "pickaxe", 0);
        GameRegistry.registerBlock(monorailMagenta, "monorailMagenta");
        LanguageRegistry.addName(monorailLightblue, "LightBlue Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailLightblue, "pickaxe", 0);
        GameRegistry.registerBlock(monorailLightblue, "monorailLightblue");
        LanguageRegistry.addName(monorailYellow, "Yellow Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailYellow, "pickaxe", 0);
        GameRegistry.registerBlock(monorailYellow, "monorailYellow");
        LanguageRegistry.addName(monorailLime, "Lime Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailLime, "pickaxe", 0);
        GameRegistry.registerBlock(monorailLime, "monorailLime");
        LanguageRegistry.addName(monorailPink, "Pink Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailPink, "pickaxe", 0);
        GameRegistry.registerBlock(monorailPink, "monorailPink");
        LanguageRegistry.addName(monorailGray, "Gray Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailGray, "pickaxe", 0);
        GameRegistry.registerBlock(monorailGray, "monorailGray");
        LanguageRegistry.addName(monorailLightgray, "LightGray Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailLightgray, "pickaxe", 0);
        GameRegistry.registerBlock(monorailLightgray, "monorailLightgray");
        LanguageRegistry.addName(monorailCyan, "Cyan Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailCyan, "pickaxe", 0);
        GameRegistry.registerBlock(monorailCyan, "monorailCyan");
        LanguageRegistry.addName(monorailPurple, "Purple Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailPurple, "pickaxe", 0);
        GameRegistry.registerBlock(monorailPurple, "monorailPurple");
        LanguageRegistry.addName(monorailBlue, "Blue Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailBlue, "pickaxe", 0);
        GameRegistry.registerBlock(monorailBlue, "monorailBlue");
        LanguageRegistry.addName(monorailBrown, "Brown Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailBrown, "pickaxe", 0);
        GameRegistry.registerBlock(monorailBrown, "monorailBrown");
        LanguageRegistry.addName(monorailGreen, "Green Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailGreen, "pickaxe", 0);
        GameRegistry.registerBlock(monorailGreen, "monorailGreen");
        LanguageRegistry.addName(monorailRed, "Red Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailRed, "pickaxe", 0);
        GameRegistry.registerBlock(monorailRed, "monorailRed");
        LanguageRegistry.addName(monorailBlack, "Black Monorail");
        //MinecraftForge.setBlockHarvestLevel(monorailBlack, "pickaxe", 0);
        GameRegistry.registerBlock(monorailBlack, "monorailBlack");
        //Triplerail//
        LanguageRegistry.addName(triplerailDiamond, "Diamond Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailDiamond, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailDiamond, "triplerailDiamond");
        LanguageRegistry.addName(triplerailGlowing, "Glowing Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailGlowing, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailGlowing, "triplerailGlowing");
        LanguageRegistry.addName(triplerailNether, "Nether Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailNether, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailNether, "triplerailNether");
        LanguageRegistry.addName(triplerailObsidian, "Obsidian Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailObsidian, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailObsidian, "triplerailObsidian");
        LanguageRegistry.addName(triplerailEmerald, "Emerald Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailEmerald, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailEmerald, "triplerailEmerald");
        LanguageRegistry.addName(triplerailLapis, "Lapis Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailLapis, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailLapis, "triplerailLapis");
        LanguageRegistry.addName(triplerailPowered, "Powered Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailPowered, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailPowered, "triplerailPowered");
        LanguageRegistry.addName(triplerailIce, "Ice Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailIce, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailIce, "triplerailIce");
        LanguageRegistry.addName(triplerailChain, "Chain Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailChain, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailChain, "triplerailChain");
        LanguageRegistry.addName(triplerailArmed, "Armed Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailArmed, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailArmed, "triplerailArmed");
        LanguageRegistry.addName(triplerailEnderPearl, "Ender Pearl Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailEnderPearl, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailEnderPearl, "triplerailEnderPearl");
        //Triple Wool Rails//
        LanguageRegistry.addName(triplerailWhite, "White Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailWhite, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailWhite, "triplerailWhite");
        LanguageRegistry.addName(triplerailOrange, "Orange Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailOrange, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailOrange, "triplerailOrange");
        LanguageRegistry.addName(triplerailMagenta, "Magenta Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailMagenta, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailMagenta, "triplerailMagenta");
        LanguageRegistry.addName(triplerailLightblue, "LightBlue Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailLightblue, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailLightblue, "triplerailLightblue");
        LanguageRegistry.addName(triplerailYellow, "Yellow Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailYellow, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailYellow, "triplerailYellow");
        LanguageRegistry.addName(triplerailLime, "Lime Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailLime, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailLime, "triplerailLime");
        LanguageRegistry.addName(triplerailPink, "Pink Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailPink, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailPink, "triplerailPink");
        LanguageRegistry.addName(triplerailGray, "Gray Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailGray, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailGray, "triplerailGray");
        LanguageRegistry.addName(triplerailLightgray, "LightGray Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailLightgray, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailLightgray, "triplerailLightgray");
        LanguageRegistry.addName(triplerailCyan, "Cyan Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailCyan, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailCyan, "triplerailCyan");
        LanguageRegistry.addName(triplerailPurple, "Purple Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailPurple, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailPurple, "triplerailPurple");
        LanguageRegistry.addName(triplerailBlue, "Blue Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailBlue, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailBlue, "triplerailBlue");
        LanguageRegistry.addName(triplerailBrown, "Brown Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailBrown, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailBrown, "triplerailBrown");
        LanguageRegistry.addName(triplerailGreen, "Green Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailGreen, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailGreen, "triplerailGreen");
        LanguageRegistry.addName(triplerailRed, "Red Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailRed, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailRed, "triplerailRed");
        LanguageRegistry.addName(triplerailBlack, "Black Triplerail");
        //MinecraftForge.setBlockHarvestLevel(triplerailBlack, "pickaxe", 0);
        GameRegistry.registerBlock(triplerailBlack, "triplerailBlack");
        
        LanguageRegistry.addName(railsCraftingTable, "Rails Crafting Table");
        GameRegistry.registerBlock(railsCraftingTable, "railsCraftingTable");
        
        //LanguageRegistry.addName(railBrake, "Rail Brake");
        //GameRegistry.registerBlock(railBrake, "railBrake");
        
        NetworkRegistry.INSTANCE.registerGuiHandler(this, guiHandlerRailsCraftingTable);
        
        //Item Registering//
        LanguageRegistry.addName(obsidianBar, "Obsidian Bar");
        GameRegistry.registerItem(obsidianBar, "obsidianBar");
        LanguageRegistry.addName(emeraldBar, "Emerald Bar");
        GameRegistry.registerItem(emeraldBar, "emeraldBar");
        LanguageRegistry.addName(diamondBar, "Diamond Bar");
        GameRegistry.registerItem(diamondBar, "diamondBar");
        LanguageRegistry.addName(lapisBar, "Lapis Lazuli Bar");
        GameRegistry.registerItem(lapisBar, "lapisBar");
        LanguageRegistry.addName(explosiveBar, "Explosive Bar");
        GameRegistry.registerItem(explosiveBar, "explosiveBar");
        LanguageRegistry.addName(ironNail, "Iron Nail");
        GameRegistry.registerItem(ironNail, "ironNail");
        LanguageRegistry.addName(goldNail, "Gold Nail");
        GameRegistry.registerItem(goldNail, "goldNail");
        LanguageRegistry.addName(diamondNail, "Diamond Nail");
        GameRegistry.registerItem(diamondNail, "diamondNail");
        LanguageRegistry.addName(emeraldNail, "Emerald Nail");
        GameRegistry.registerItem(emeraldNail, "emeraldNail");
        LanguageRegistry.addName(obsidianNail, "Obsidian Nail");
        GameRegistry.registerItem(obsidianNail, "obsidianNail");
        LanguageRegistry.addName(netherrackNail, "Netherrack Nail");
        GameRegistry.registerItem(netherrackNail, "netherrackNail");
        LanguageRegistry.addName(woolenNail, "Woolen Nail");
        GameRegistry.registerItem(woolenNail, "woolenNail");
        LanguageRegistry.addName(netherIngot, "Netherrack Ingot");
        GameRegistry.registerItem(netherIngot, "netherIngot");
        LanguageRegistry.addName(railIronBase, "Iron Rail Base");
        GameRegistry.registerItem(railIronBase, "railIronBase");
        LanguageRegistry.addName(railDiamondBase, "Diamond Rail Base");
        GameRegistry.registerItem(railDiamondBase, "railDiamondBase");
        LanguageRegistry.addName(railObsidianBase, "Obsidian Rail Base");
        GameRegistry.registerItem(railObsidianBase, "railObsidianBase");
        LanguageRegistry.addName(railNetherrackBase, "Nether Rail Base");
        GameRegistry.registerItem(railNetherrackBase, "railNetherrackBase");
        LanguageRegistry.addName(railEmeraldBase, "Emerald Rail Base");
        GameRegistry.registerItem(railEmeraldBase, "railEmeraldBase");
        LanguageRegistry.addName(railLapisBase, "Lapis Lazuli Rail Base");
        GameRegistry.registerItem(railLapisBase, "railLapisBase");
        LanguageRegistry.addName(railGoldBase, "Golden Rail Base");
        GameRegistry.registerItem(railGoldBase, "railGoldBase");
        LanguageRegistry.addName(railChainBase, "Chain Rail Base");
        GameRegistry.registerItem(railChainBase, "railChainBase");
        LanguageRegistry.addName(railArmedBase, "Armed Rail Base");
        GameRegistry.registerItem(railArmedBase, "railArmedBase");
        LanguageRegistry.addName(railIceBase, "Ice Rail Base");
        GameRegistry.registerItem(railIceBase, "railIceBase");
        LanguageRegistry.addName(railEnderPearlBase, "Ender Pearl Rail Base");
        GameRegistry.registerItem(railEnderPearlBase, "railEnderPearlBase");
        LanguageRegistry.addName(obsidianChunk, "Obsidian Chunk");
        GameRegistry.registerItem(obsidianChunk, "obsidianChunk");
        //LanguageRegistry.addName(minecartWhite, "Minecart White");
        //GameRegistry.registerItem(minecartWhite, "minecartWhite");
        //LanguageRegistry.addName(minecartOrange, "Minecart Orange");
        //GameRegistry.registerItem(minecartOrange, "minecartOrange");
        //LanguageRegistry.addName(minecartMagenta, "Minecart Magenta");
        //GameRegistry.registerItem(minecartMagenta, "minecartMagenta");
        //LanguageRegistry.addName(minecartLightblue, "Minecart Lightblue");
        //GameRegistry.registerItem(minecartLightblue, "minecartLightblue");
        //LanguageRegistry.addName(minecartYellow, "Minecart Yellow");
        //GameRegistry.registerItem(minecartYellow, "minecartYellow");
        //LanguageRegistry.addName(minecartLime, "Minecart Lime");
        //GameRegistry.registerItem(minecartLime, "minecartLime");
        //LanguageRegistry.addName(minecartPink, "Minecart Pink");
        //GameRegistry.registerItem(minecartPink, "minecartPink");
        //LanguageRegistry.addName(minecartGray, "Minecart Gray");
        //GameRegistry.registerItem(minecartGray, "minecartGray");
        //LanguageRegistry.addName(minecartLightgray, "Minecart Lightgray");
        //GameRegistry.registerItem(minecartLightgray, "minecartLightgray");
        //LanguageRegistry.addName(minecartCyan, "Minecart Cyan");
        //GameRegistry.registerItem(minecartCyan, "minecartCyan");
        //LanguageRegistry.addName(minecartPurple, "Minecart Purple");
        //GameRegistry.registerItem(minecartPurple, "minecartPurple");
        //LanguageRegistry.addName(minecartBlue, "Minecart Blue");
        //GameRegistry.registerItem(minecartBlue, "minecartBlue");
        //LanguageRegistry.addName(minecartBrown, "Minecart Brown");
        //GameRegistry.registerItem(minecartBrown, "minecartBrown");
        //LanguageRegistry.addName(minecartGreen, "Minecart Green");
        //GameRegistry.registerItem(minecartGreen, "minecartGreen");
        //LanguageRegistry.addName(minecartRed, "Minecart Red");
        //GameRegistry.registerItem(minecartRed, "minecartRed");
        //LanguageRegistry.addName(minecartBlack, "Minecart Black");
        //GameRegistry.registerItem(minecartBlack, "minecartBlack");
        
        //Tile Entity Registering//
        
        //GameRegistry.registerPlayerTracker(new PlayerJoin());
        
        //Recipe Registering//
        
        //Block Recipes//
        GameRegistry.addRecipe(new ItemStack(whiteWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.whiteclothStack);
        GameRegistry.addRecipe(new ItemStack(orangeWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.orangeclothStack);
        GameRegistry.addRecipe(new ItemStack(magentaWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.magentaclothStack);
        GameRegistry.addRecipe(new ItemStack(lightblueWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.lightblueclothStack);
        GameRegistry.addRecipe(new ItemStack(yellowWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.yellowclothStack);
        GameRegistry.addRecipe(new ItemStack(limeWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.limeclothStack);
        GameRegistry.addRecipe(new ItemStack(pinkWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.pinkclothStack);
        GameRegistry.addRecipe(new ItemStack(grayWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.grayclothStack);
        GameRegistry.addRecipe(new ItemStack(lightgrayWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.lightgrayclothStack);
        GameRegistry.addRecipe(new ItemStack(cyanWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.cyanclothStack);
        GameRegistry.addRecipe(new ItemStack(purpleWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.purpleclothStack);
        GameRegistry.addRecipe(new ItemStack(blueWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.blueclothStack);
        GameRegistry.addRecipe(new ItemStack(brownWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.brownclothStack);
        GameRegistry.addRecipe(new ItemStack(greenWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.greenclothStack);
        GameRegistry.addRecipe(new ItemStack(redWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.redclothStack);
        GameRegistry.addRecipe(new ItemStack(blackWoolRail, 16), "x x", "xyx", "x x", 'x', Stacks.ironIngotStack, 'y', Stacks.blackclothStack);
        GameRegistry.addRecipe(new ItemStack(railsCraftingTable, 1), "xyx", "zzz", "aba", 'x', Stacks.ironIngotStack, 'y', Stacks.railStack, 'z', Stacks.greenclothStack, 'a', Stacks.ironNailStack, 'b', Stacks.workbenchStack);
        //Item Recipes//
        GameRegistry.addRecipe(new ItemStack(obsidianBar, 8), "  x", " x ", "x  ", 'x', Stacks.obsidianChunkStack);
        GameRegistry.addRecipe(new ItemStack(diamondBar, 8), "  x", " x ", "x  ", 'x', Stacks.diamondStack);
        GameRegistry.addRecipe(new ItemStack(emeraldBar, 8), "  x", " x ", "x  ", 'x', Stacks.emeraldStack);
        GameRegistry.addRecipe(new ItemStack(lapisBar, 8), "  x", " x ", "x  ", 'x', Stacks.lapisStack);
        GameRegistry.addRecipe(new ItemStack(explosiveBar, 8), "  x", " y ", "x  ", 'x', Stacks.quartzStack, 'y', Stacks.gunpowderStack);
        GameRegistry.addRecipe(new ItemStack(netherIngot, 1), "x ", " x", 'x', Stacks.netherrackStack);
        GameRegistry.addRecipe(new ItemStack(ironNail, 4), " x", "y ", 'x', Stacks.ironIngotStack, 'y', Stacks.stoneStack);
        GameRegistry.addRecipe(new ItemStack(goldNail, 4), " x", "y ", 'x', Stacks.goldIngotStack, 'y', Stacks.stoneStack);
        GameRegistry.addRecipe(new ItemStack(diamondNail, 8), " x", "y ", 'x', Stacks.diamondStack, 'y', Stacks.stoneStack);
        GameRegistry.addRecipe(new ItemStack(emeraldNail, 8), " x", "y ", 'x', Stacks.emeraldStack, 'y', Stacks.stoneStack);
        GameRegistry.addRecipe(new ItemStack(obsidianNail, 4), " x", "y ", 'x', Stacks.obsidianChunkStack, 'y', Stacks.stoneStack);
        GameRegistry.addRecipe(new ItemStack(netherrackNail, 4), " x", "y ", 'x', Stacks.netherIngotStack, 'y', Stacks.stoneStack);
        GameRegistry.addRecipe(new ItemStack(woolenNail, 4), " x", "y ", 'x', Stacks.whiteclothStack, 'y', Stacks.stoneStack);
        GameRegistry.addRecipe(new ItemStack(railIronBase, 4), "x", "x", "x", 'x', Stacks.ironIngotStack);
        GameRegistry.addRecipe(new ItemStack(railDiamondBase, 4), "x", "x", "x", 'x', Stacks.diamondBarStack);
        GameRegistry.addRecipe(new ItemStack(railObsidianBase, 4), "x", "x", "x", 'x', Stacks.obsidianBarStack);
        GameRegistry.addRecipe(new ItemStack(railNetherrackBase, 4), "x", "x", "x", 'x', Stacks.netherIngotStack);
        GameRegistry.addRecipe(new ItemStack(railEmeraldBase, 4), "x", "x", "x", 'x', Stacks.emeraldBarStack);
        GameRegistry.addRecipe(new ItemStack(railLapisBase, 4), "x", "x", "x", 'x', Stacks.lapisBarStack);
        GameRegistry.addRecipe(new ItemStack(railGoldBase, 4), "x", "x", "x", 'x', Stacks.goldIngotStack);
        GameRegistry.addRecipe(new ItemStack(railArmedBase, 8), "x", "x", "x", 'x', Stacks.explosiveBarStack);
        GameRegistry.addRecipe(new ItemStack(railChainBase, 4), "x", "y", "x", 'x', Stacks.ironIngotStack, 'y', Stacks.obsidianChunkStack);
        GameRegistry.addRecipe(new ItemStack(railIceBase, 4), "x", "x", "x", 'x', Stacks.iceStack);
        GameRegistry.addRecipe(new ItemStack(railEnderPearlBase, 8), "x", "x", "x", 'x', Stacks.enderPearlStack);
        GameRegistry.addRecipe(new ItemStack(Blocks.ice, 16), " x ", "xyx", " x ", 'x', Stacks.snowStack, 'y', Stacks.waterBucketStack);
        GameRegistry.addShapelessRecipe(new ItemStack(obsidianChunk, 4), Stacks.obsidianStack, Stacks.cobblestoneStack);
        //Tabs
        LanguageRegistry.instance().addStringLocalization("itemGroup.tabNormalRails", "en_US", "Normal Rails");
        whiteWoolRail.setCreativeTab(this.tabNormalRails);
        orangeWoolRail.setCreativeTab(this.tabNormalRails);
        magentaWoolRail.setCreativeTab(this.tabNormalRails);
        lightblueWoolRail.setCreativeTab(this.tabNormalRails);
        yellowWoolRail.setCreativeTab(this.tabNormalRails);
        limeWoolRail.setCreativeTab(this.tabNormalRails);
        pinkWoolRail.setCreativeTab(this.tabNormalRails);
        grayWoolRail.setCreativeTab(this.tabNormalRails);
        lightgrayWoolRail.setCreativeTab(this.tabNormalRails);
        cyanWoolRail.setCreativeTab(this.tabNormalRails);
        purpleWoolRail.setCreativeTab(this.tabNormalRails);
        blueWoolRail.setCreativeTab(this.tabNormalRails);
        brownWoolRail.setCreativeTab(this.tabNormalRails);
        greenWoolRail.setCreativeTab(this.tabNormalRails);
        redWoolRail.setCreativeTab(this.tabNormalRails);
        blackWoolRail.setCreativeTab(this.tabNormalRails);
        diamondRail.setCreativeTab(this.tabNormalRails);
        emeraldRail.setCreativeTab(this.tabNormalRails);
        obsidianRail.setCreativeTab(this.tabNormalRails);
        lapisRail.setCreativeTab(this.tabNormalRails);
        glowstoneRail.setCreativeTab(this.tabNormalRails);
        enderPearlRail.setCreativeTab(this.tabNormalRails);
        armedRail.setCreativeTab(this.tabNormalRails);
        chainRail.setCreativeTab(this.tabNormalRails);
        iceRail.setCreativeTab(this.tabNormalRails);
        diamondNetherRail.setCreativeTab(this.tabNormalRails);
        diamondObsidianRail.setCreativeTab(this.tabNormalRails);
        brickRail.setCreativeTab(this.tabNormalRails);
        netherStarRail.setCreativeTab(this.tabNormalRails);
        LanguageRegistry.instance().addStringLocalization("itemGroup.tabMonoRails", "en_US", "Mono Rails");
        monorailWhite.setCreativeTab(this.tabMonoRails);
        monorailOrange.setCreativeTab(this.tabMonoRails);
        monorailMagenta.setCreativeTab(this.tabMonoRails);
        monorailLightblue.setCreativeTab(this.tabMonoRails);
        monorailYellow.setCreativeTab(this.tabMonoRails);
        monorailLime.setCreativeTab(this.tabMonoRails);
        monorailPink.setCreativeTab(this.tabMonoRails);
        monorailGray.setCreativeTab(this.tabMonoRails);
        monorailLightgray.setCreativeTab(this.tabMonoRails);
        monorailCyan.setCreativeTab(this.tabMonoRails);
        monorailPurple.setCreativeTab(this.tabMonoRails);
        monorailBlue.setCreativeTab(this.tabMonoRails);
        monorailBrown.setCreativeTab(this.tabMonoRails);
        monorailGreen.setCreativeTab(this.tabMonoRails);
        monorailRed.setCreativeTab(this.tabMonoRails);
        monorailBlack.setCreativeTab(this.tabMonoRails);
        monorailDiamond.setCreativeTab(this.tabMonoRails);
        monorailEmerald.setCreativeTab(this.tabMonoRails);
        monorailObsidian.setCreativeTab(this.tabMonoRails);
        monorailLapis.setCreativeTab(this.tabMonoRails);
        monorailGlowing.setCreativeTab(this.tabMonoRails);
        monorailEnderPearl.setCreativeTab(this.tabMonoRails);
        monorailArmed.setCreativeTab(this.tabMonoRails);
        monorailChain.setCreativeTab(this.tabMonoRails);
        monorailIce.setCreativeTab(this.tabMonoRails);
        monorailPowered.setCreativeTab(this.tabMonoRails);
        monorailGold.setCreativeTab(this.tabMonoRails);
        monorailNether.setCreativeTab(this.tabMonoRails);
        monorailRedGreen.setCreativeTab(this.tabMonoRails);
        monorailYellowBlue.setCreativeTab(this.tabMonoRails);
        monorailGrayOrange.setCreativeTab(this.tabMonoRails);
        LanguageRegistry.instance().addStringLocalization("itemGroup.tabTripleRails", "en_US", "Triple Rails");
        triplerailWhite.setCreativeTab(this.tabTripleRails);
        triplerailOrange.setCreativeTab(this.tabTripleRails);
        triplerailMagenta.setCreativeTab(this.tabTripleRails);
        triplerailLightblue.setCreativeTab(this.tabTripleRails);
        triplerailYellow.setCreativeTab(this.tabTripleRails);
        triplerailLime.setCreativeTab(this.tabTripleRails);
        triplerailPink.setCreativeTab(this.tabTripleRails);
        triplerailGray.setCreativeTab(this.tabTripleRails);
        triplerailLightgray.setCreativeTab(this.tabTripleRails);
        triplerailCyan.setCreativeTab(this.tabTripleRails);
        triplerailPurple.setCreativeTab(this.tabTripleRails);
        triplerailBlue.setCreativeTab(this.tabTripleRails);
        triplerailBrown.setCreativeTab(this.tabTripleRails);
        triplerailGreen.setCreativeTab(this.tabTripleRails);
        triplerailRed.setCreativeTab(this.tabTripleRails);
        triplerailBlack.setCreativeTab(this.tabTripleRails);
        triplerailDiamond.setCreativeTab(this.tabTripleRails);
        triplerailEmerald.setCreativeTab(this.tabTripleRails);
        triplerailObsidian.setCreativeTab(this.tabTripleRails);
        triplerailLapis.setCreativeTab(this.tabTripleRails);
        triplerailGlowing.setCreativeTab(this.tabTripleRails);
        triplerailEnderPearl.setCreativeTab(this.tabTripleRails);
        triplerailArmed.setCreativeTab(this.tabTripleRails);
        triplerailChain.setCreativeTab(this.tabTripleRails);
        triplerailIce.setCreativeTab(this.tabTripleRails);
        triplerailPowered.setCreativeTab(this.tabTripleRails);
        triplerailNether.setCreativeTab(this.tabTripleRails);
        proxy.registerRenderers();
//GameRegistry.registerTileEntity(TileEntityRailBrakeEntity.class, "railBrake");
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
        // Stub Method
    }
}